name: lmp_calculator
description: Hidden gallery calculator with decoy, fingerprint & stealth mode.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  local_auth: ^2.1.0
  file_picker: ^5.2.4
  path_provider: ^2.0.11
  permission_handler: ^10.2.0

flutter:
  uses-material-design: true
